name: Publish GitHub Packages
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Set env variable from latest maven version
        run: >
          echo "RELEASE_VERSION=$( \
            curl https://repo.mineinabyss.com/releases/com/nexomc/nexolibs/maven-metadata.xml | \
            grep -oP '(?!<latest>)[\d\.]*(?=</latest>)' \
          )" >> $GITHUB_ENV
      - name: Run gradle build and publish
        run: gradle publish -PmineinabyssMavenUsername=${{ secrets.MAVEN_USERNAME }} -PmineinabyssMavenPassword=${{ secrets.MAVEN_PASSWORD }}
      - name: Get version from gradle
        shell: bash
        id: extract_version
        run: |
          version=`gradle properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'`
          echo "::set-output name=version::$version"
